# Generated by Django 4.2.1 on 2023-05-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_dislike_post_like_alter_comment_dislikes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='content_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
